4name: r_go_humannet
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.3.3
  - r-readr=2.1.5
  - r-dplyr=1.1.4
  - r-stringr=1.5.1
  - r-tidyr=1.3.1
  - bioconductor-biomart=2.58.0
  - r-curl=5.1.0
  - r-httr=1.4.7
  - bioconductor-annotationdbi=1.64.1
  - bioconductor-go.db=3.18.0
  - bioconductor-org.hs.eg.db=3.18.0
